require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Template::TemplatesController do

  # This should return the minimal set of attributes required to create a valid
  # Template::Template. As you add validations to Template::Template, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "template_cate" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Template::TemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all template_templates as @template_templates" do
      template = Template::Template.create! valid_attributes
      get :index, {}, valid_session
      assigns(:template_templates).should eq([template])
    end
  end

  describe "GET show" do
    it "assigns the requested template_template as @template_template" do
      template = Template::Template.create! valid_attributes
      get :show, {:id => template.to_param}, valid_session
      assigns(:template_template).should eq(template)
    end
  end

  describe "GET new" do
    it "assigns a new template_template as @template_template" do
      get :new, {}, valid_session
      assigns(:template_template).should be_a_new(Template::Template)
    end
  end

  describe "GET edit" do
    it "assigns the requested template_template as @template_template" do
      template = Template::Template.create! valid_attributes
      get :edit, {:id => template.to_param}, valid_session
      assigns(:template_template).should eq(template)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Template::Template" do
        expect {
          post :create, {:template_template => valid_attributes}, valid_session
        }.to change(Template::Template, :count).by(1)
      end

      it "assigns a newly created template_template as @template_template" do
        post :create, {:template_template => valid_attributes}, valid_session
        assigns(:template_template).should be_a(Template::Template)
        assigns(:template_template).should be_persisted
      end

      it "redirects to the created template_template" do
        post :create, {:template_template => valid_attributes}, valid_session
        response.should redirect_to(Template::Template.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved template_template as @template_template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Template::Template.any_instance.stub(:save).and_return(false)
        post :create, {:template_template => { "template_cate" => "invalid value" }}, valid_session
        assigns(:template_template).should be_a_new(Template::Template)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Template::Template.any_instance.stub(:save).and_return(false)
        post :create, {:template_template => { "template_cate" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested template_template" do
        template = Template::Template.create! valid_attributes
        # Assuming there are no other template_templates in the database, this
        # specifies that the Template::Template created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Template::Template.any_instance.should_receive(:update).with({ "template_cate" => "" })
        put :update, {:id => template.to_param, :template_template => { "template_cate" => "" }}, valid_session
      end

      it "assigns the requested template_template as @template_template" do
        template = Template::Template.create! valid_attributes
        put :update, {:id => template.to_param, :template_template => valid_attributes}, valid_session
        assigns(:template_template).should eq(template)
      end

      it "redirects to the template_template" do
        template = Template::Template.create! valid_attributes
        put :update, {:id => template.to_param, :template_template => valid_attributes}, valid_session
        response.should redirect_to(template)
      end
    end

    describe "with invalid params" do
      it "assigns the template_template as @template_template" do
        template = Template::Template.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Template::Template.any_instance.stub(:save).and_return(false)
        put :update, {:id => template.to_param, :template_template => { "template_cate" => "invalid value" }}, valid_session
        assigns(:template_template).should eq(template)
      end

      it "re-renders the 'edit' template" do
        template = Template::Template.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Template::Template.any_instance.stub(:save).and_return(false)
        put :update, {:id => template.to_param, :template_template => { "template_cate" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested template_template" do
      template = Template::Template.create! valid_attributes
      expect {
        delete :destroy, {:id => template.to_param}, valid_session
      }.to change(Template::Template, :count).by(-1)
    end

    it "redirects to the template_templates list" do
      template = Template::Template.create! valid_attributes
      delete :destroy, {:id => template.to_param}, valid_session
      response.should redirect_to(template_templates_url)
    end
  end

end
