require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BizSitesController do

  # This should return the minimal set of attributes required to create a valid
  # BizSite. As you add validations to BizSite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BizSitesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all biz_sites as @biz_sites" do
      biz_site = BizSite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:biz_sites).should eq([biz_site])
    end
  end

  describe "GET show" do
    it "assigns the requested biz_site as @biz_site" do
      biz_site = BizSite.create! valid_attributes
      get :show, {:id => biz_site.to_param}, valid_session
      assigns(:biz_site).should eq(biz_site)
    end
  end

  describe "GET new" do
    it "assigns a new biz_site as @biz_site" do
      get :new, {}, valid_session
      assigns(:biz_site).should be_a_new(BizSite)
    end
  end

  describe "GET edit" do
    it "assigns the requested biz_site as @biz_site" do
      biz_site = BizSite.create! valid_attributes
      get :edit, {:id => biz_site.to_param}, valid_session
      assigns(:biz_site).should eq(biz_site)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BizSite" do
        expect {
          post :create, {:biz_site => valid_attributes}, valid_session
        }.to change(BizSite, :count).by(1)
      end

      it "assigns a newly created biz_site as @biz_site" do
        post :create, {:biz_site => valid_attributes}, valid_session
        assigns(:biz_site).should be_a(BizSite)
        assigns(:biz_site).should be_persisted
      end

      it "redirects to the created biz_site" do
        post :create, {:biz_site => valid_attributes}, valid_session
        response.should redirect_to(BizSite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved biz_site as @biz_site" do
        # Trigger the behavior that occurs when invalid params are submitted
        BizSite.any_instance.stub(:save).and_return(false)
        post :create, {:biz_site => { "title" => "invalid value" }}, valid_session
        assigns(:biz_site).should be_a_new(BizSite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BizSite.any_instance.stub(:save).and_return(false)
        post :create, {:biz_site => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested biz_site" do
        biz_site = BizSite.create! valid_attributes
        # Assuming there are no other biz_sites in the database, this
        # specifies that the BizSite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BizSite.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => biz_site.to_param, :biz_site => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested biz_site as @biz_site" do
        biz_site = BizSite.create! valid_attributes
        put :update, {:id => biz_site.to_param, :biz_site => valid_attributes}, valid_session
        assigns(:biz_site).should eq(biz_site)
      end

      it "redirects to the biz_site" do
        biz_site = BizSite.create! valid_attributes
        put :update, {:id => biz_site.to_param, :biz_site => valid_attributes}, valid_session
        response.should redirect_to(biz_site)
      end
    end

    describe "with invalid params" do
      it "assigns the biz_site as @biz_site" do
        biz_site = BizSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BizSite.any_instance.stub(:save).and_return(false)
        put :update, {:id => biz_site.to_param, :biz_site => { "title" => "invalid value" }}, valid_session
        assigns(:biz_site).should eq(biz_site)
      end

      it "re-renders the 'edit' template" do
        biz_site = BizSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BizSite.any_instance.stub(:save).and_return(false)
        put :update, {:id => biz_site.to_param, :biz_site => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested biz_site" do
      biz_site = BizSite.create! valid_attributes
      expect {
        delete :destroy, {:id => biz_site.to_param}, valid_session
      }.to change(BizSite, :count).by(-1)
    end

    it "redirects to the biz_sites list" do
      biz_site = BizSite.create! valid_attributes
      delete :destroy, {:id => biz_site.to_param}, valid_session
      response.should redirect_to(biz_sites_url)
    end
  end

end
