require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SiteCommentsController do

  # This should return the minimal set of attributes required to create a valid
  # SiteComment. As you add validations to SiteComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SiteCommentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all site_comments as @site_comments" do
      site_comment = SiteComment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:site_comments).should eq([site_comment])
    end
  end

  describe "GET show" do
    it "assigns the requested site_comment as @site_comment" do
      site_comment = SiteComment.create! valid_attributes
      get :show, {:id => site_comment.to_param}, valid_session
      assigns(:site_comment).should eq(site_comment)
    end
  end

  describe "GET new" do
    it "assigns a new site_comment as @site_comment" do
      get :new, {}, valid_session
      assigns(:site_comment).should be_a_new(SiteComment)
    end
  end

  describe "GET edit" do
    it "assigns the requested site_comment as @site_comment" do
      site_comment = SiteComment.create! valid_attributes
      get :edit, {:id => site_comment.to_param}, valid_session
      assigns(:site_comment).should eq(site_comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SiteComment" do
        expect {
          post :create, {:site_comment => valid_attributes}, valid_session
        }.to change(SiteComment, :count).by(1)
      end

      it "assigns a newly created site_comment as @site_comment" do
        post :create, {:site_comment => valid_attributes}, valid_session
        assigns(:site_comment).should be_a(SiteComment)
        assigns(:site_comment).should be_persisted
      end

      it "redirects to the created site_comment" do
        post :create, {:site_comment => valid_attributes}, valid_session
        response.should redirect_to(SiteComment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved site_comment as @site_comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteComment.any_instance.stub(:save).and_return(false)
        post :create, {:site_comment => { "user" => "invalid value" }}, valid_session
        assigns(:site_comment).should be_a_new(SiteComment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteComment.any_instance.stub(:save).and_return(false)
        post :create, {:site_comment => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested site_comment" do
        site_comment = SiteComment.create! valid_attributes
        # Assuming there are no other site_comments in the database, this
        # specifies that the SiteComment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SiteComment.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => site_comment.to_param, :site_comment => { "user" => "" }}, valid_session
      end

      it "assigns the requested site_comment as @site_comment" do
        site_comment = SiteComment.create! valid_attributes
        put :update, {:id => site_comment.to_param, :site_comment => valid_attributes}, valid_session
        assigns(:site_comment).should eq(site_comment)
      end

      it "redirects to the site_comment" do
        site_comment = SiteComment.create! valid_attributes
        put :update, {:id => site_comment.to_param, :site_comment => valid_attributes}, valid_session
        response.should redirect_to(site_comment)
      end
    end

    describe "with invalid params" do
      it "assigns the site_comment as @site_comment" do
        site_comment = SiteComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_comment.to_param, :site_comment => { "user" => "invalid value" }}, valid_session
        assigns(:site_comment).should eq(site_comment)
      end

      it "re-renders the 'edit' template" do
        site_comment = SiteComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteComment.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_comment.to_param, :site_comment => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested site_comment" do
      site_comment = SiteComment.create! valid_attributes
      expect {
        delete :destroy, {:id => site_comment.to_param}, valid_session
      }.to change(SiteComment, :count).by(-1)
    end

    it "redirects to the site_comments list" do
      site_comment = SiteComment.create! valid_attributes
      delete :destroy, {:id => site_comment.to_param}, valid_session
      response.should redirect_to(site_comments_url)
    end
  end

end
